name: notesgpt
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  googleapis: ^10.1.0
  googleapis_auth: ^1.4.0

  english_words: ^4.0.0
  provider: ^6.0.0

  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.1.4
  firebase_core: ^2.7.0
  _flutterfire_internals: ^1.0.16
  firebase_auth: ^4.2.9
  firebase: ^9.0.3
  auth: ^8.2.0+02
  cloud_firestore: ^4.4.3
  get: ^4.6.1 # add this line
  awesome_snackbar_content: ^0.1.2
  http: ^0.13.5
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
      - assets/noteslogo.png
      - assets/apple.png
      - assets/google.png
      - assets/noteslogo2.png
      - assets/noteslogo3.png
      - assets/signup.png
      - assets/login.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf

