name: myapp
description: A exported flutter project from FUNCTION12

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter  
  
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true
  
  assets:
    - assets/page-1/images/icon.png
    - assets/page-1/images/social-icon-apple.png
    - assets/page-1/images/icon-KQ9.png
    - assets/page-1/images/icon-zNh.png
    - assets/page-1/images/icon-cy3.png
    - assets/page-1/images/icon-4x5.png
    - assets/page-1/images/icon-vSR.png
    - assets/page-1/images/icon-qxH.png
    - assets/page-1/images/sign-up.png
    - assets/page-1/images/bg.png
    - assets/page-1/images/group-80.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/icon-rJH.png
    - assets/page-1/images/icon-Snq.png
    - assets/page-1/images/icon-C9B.png
    - assets/page-1/images/rectangle-52.png
    - assets/page-1/images/icon-A5T.png
    - assets/page-1/images/icon-PXB.png
    - assets/page-1/images/icon-microphone-2.png
    - assets/page-1/images/rectangle-59.png
    - assets/page-1/images/social-icon-apple-D7T.png
    - assets/page-1/images/vector-GFw.png
    - assets/page-1/images/noteslogoapp-01-1.png
    - assets/page-1/images/noteslogoapp-01-1-zG5.png

  
  

  
  

  
    
  
  
  
  
  
  
  
  
  
  #
  
  
